<a href="https://colab.research.google.com/github/vudinhhoan213/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np

LISTS

In [5]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

NUMPY ARRAYS


In [11]:
np1 = np.random.rand(3,4)
np1

array([[0.41655465, 0.04937765, 0.77203973, 0.08584392],
       [0.85390785, 0.54356758, 0.42916661, 0.99315157],
       [0.8325681 , 0.52113575, 0.95730566, 0.79560268]])

In [9]:
np1.dtype

dtype('float64')

TENSORS


In [17]:
tensor_2d = torch.randn(3,4)
tensor_2d
##tensor_2d.dtype

tensor([[ 0.1436,  0.3055, -0.2880, -0.2423],
        [ 0.9810,  1.6970,  0.7873, -0.5716],
        [-0.7060, -0.4864,  2.8759,  0.0193]])

In [13]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4166, 0.0494, 0.7720, 0.0858],
        [0.8539, 0.5436, 0.4292, 0.9932],
        [0.8326, 0.5211, 0.9573, 0.7956]], dtype=torch.float64)